name: Test, build, and deploy KenyAlysis
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest
    outputs:
      js_file: ${{steps.publish.outputs.js_file}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: key-${{hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build the project
        run: npm run build
        working-directory: frontend

      - name: Upload the artifacts(dist folder)
        uses: actions/upload-artifacts@v4
        with:
          path: frontend/dist

          # I may want this job to produce an output
      - name: Publish js file
        id: publish
        run: echo "js_file=$(find frontend/dist/assets/*.js -type f | head -n 1)" >> $GITHUB_OUTPUT # This value should persist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v4
        with:
          path: frontend/dist

      - name: Output JS file
        run: echo "${{needs.build.outputs.js_file}}"
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY_ID}}
          aws-region: eu-north-1
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://${{secrets.AWS_S3_BUCKET_NAME}} --delete
