name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend # Path to frontend folder
        run: npm install

      - name: Start application server for Cypress tests
        working-directory: ./frontend # Path to frontend folder
        run: npm run dev &
        env:
          NODE_ENV: test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # Run tests in Chrome browser
          headless: true   # Run tests in headless mode
          wait-on: "http://localhost:5173" # Wait for the app to start
